name: Blog CLA Contributor

on:
  pull_request:
    types: [closed]

jobs:
  check-cla-status:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Check commit status for CLA (using PR head SHA)
        run: |
          HEAD_SHA="${{ github.event.pull_request.head.sha }}"
          echo "🔍 Checking CLA status for PR Head Commit SHA: $HEAD_SHA"

          STATUS_URL="https://api.github.com/repos/${{ github.repository }}/commits/$HEAD_SHA/status"
          echo "Fetching: $STATUS_URL"

          STATUS_JSON=$(curl -s -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" "$STATUS_URL")
          echo "$STATUS_JSON" | jq

          STATE=$(echo "$STATUS_JSON" | jq -r '.statuses[] | select(.context == "license/cla") | .state')

          if [[ "$STATE" != "success" ]]; then
            echo "❌ CLA not signed or status not successful. Current state: $STATE"
            exit 1
          fi

          echo "✅ CLA signed and status: $STATE"
