name: Blog CLA Contributor

on:
  pull_request:
    types: [closed]

jobs:
  check-cla-status:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Check commit status for CLA
        id: cla_commit_status
        run: |
          SHA="${{ github.event.pull_request.merge_commit_sha }}"
          REPO="${{ github.repository }}"
          echo "🔍 Checking commit status for SHA: $SHA"

          STATUS=$(curl -s -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/$REPO/commits/$SHA/status")

          echo "$STATUS" | jq .

          CLA_STATUS=$(echo "$STATUS" | jq -r '.statuses[] | select(.context == "license/cla") | .state')

          if [ "$CLA_STATUS" == "success" ]; then
            echo "✅ CLA check (license/cla) passed."
            echo "cla_passed=true" >> $GITHUB_OUTPUT
          else
            echo "❌ CLA check not passed or not found."
            echo "cla_passed=false" >> $GITHUB_OUTPUT
          fi
