name: Blog CLA Contributor

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  post-to-wordpress:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      WP_TOKEN: ${{ secrets.WP_TOKEN }}
      WP_SITE: ${{ secrets.WP_SITE }}

    steps:
      - name: Check if CLA label exists
        id: cla_check
        run: |
          echo "🔍 Checking for CLA label..."
          LABELS_JSON='${{ toJson(github.event.pull_request.labels) }}'
          echo "PR Labels: $LABELS_JSON"
          if echo "$LABELS_JSON" | grep -iq 'license/cla'; then
            echo "✅ CLA label found."
            echo "cla_passed=true" >> $GITHUB_OUTPUT
          else
            echo "❌ CLA label not found."
            echo "cla_passed=false" >> $GITHUB_OUTPUT
          fi

      - name: Post to WordPress (avoid duplicates)
        if: steps.cla_check.outputs.cla_passed == 'true'
        run: |
          LOGIN="${{ github.event.pull_request.user.login }}"
          AVATAR="https://github.com/$LOGIN.png"
          PROFILE="https://github.com/$LOGIN"
          REPO="${{ github.repository }}"
          TITLE="New Contributor: @$LOGIN"
          CONTENT="<p><a href=\"$PROFILE\">@$LOGIN</a> signed the CLA and contributed to <code>$REPO</code>.</p><p><img src=\"$AVATAR\" style=\"max-width:100px;border-radius:50%;\" /></p>"

          echo "🔍 Checking WordPress for existing post about @$LOGIN..."

          EXISTS=$(curl -s -G \
            -H "Authorization: Bearer $WP_TOKEN" \
            --data-urlencode "search=@$LOGIN" \
            "https://public-api.wordpress.com/rest/v1.1/sites/$WP_SITE/posts/" \
            | jq '.posts | map(select(.title | contains("@'"$LOGIN"'"))) | length')

          if [ "$EXISTS" -eq 0 ]; then
            echo "📝 No post found. Publishing..."
            curl -X POST https://public-api.wordpress.com/rest/v1.1/sites/$WP_SITE/posts/new \
              -H "Authorization: Bearer $WP_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$(jq -n --arg title "$TITLE" --arg content "$CONTENT" '{title: $title, content: $content, status: "publish"}')"
          else
            echo "✅ Contributor @$LOGIN already has a blog post. Skipping."
          fi
