name: Email CLA Contributor Post

on:
  pull_request:
    types: [closed]

permissions:
  contents: read

jobs:
  email-wordpress-post:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Install tools
        run: |
          sudo apt-get update && sudo apt-get install -y sendmail jq curl

      - name: Send CLA blog post if not already sent
        env:
          EMAIL_TO: ${{ secrets.WP_POST_BY_EMAIL }}
          GIST_ID: ${{ secrets.GIST_ID }}
          GIST_TOKEN: ${{ secrets.GIST_TOKEN }}
        run: |
          LOGIN="${{ github.event.pull_request.user.login }}"
          REPO="${{ github.repository }}"
          GIST_API="https://api.github.com/gists/$GIST_ID"

          echo "Checking if @$LOGIN already exists in Gist..."

          # Get current posted users from the Gist
          curl -s -H "Authorization: token $GIST_TOKEN" $GIST_API > gist.json
          FILE_NAME=$(jq -r '.files | keys[0]' gist.json)
          CONTENT=$(jq -r ".files[\"$FILE_NAME\"].content" gist.json)

          # Check if user already exists
          if echo "$CONTENT" | jq -e ".[] | select(. == \"$LOGIN\")" > /dev/null; then
            echo "Skipping... @$LOGIN already posted."
            exit 0
          fi

          # Send the email
          SUBJECT="New CLA Contributor: @$LOGIN"
          BODY="[status draft]\n\n@$LOGIN signed the CLA and contributed to \`$REPO\`.\nGitHub: https://github.com/$LOGIN"

          echo -e "Subject: $SUBJECT\n\n$BODY" | sendmail "$EMAIL_TO"
          echo "Email sent successfully for @$LOGIN"

          # Add to list and update Gist
          UPDATED_JSON=$(echo "$CONTENT" | jq ". + [\"$LOGIN\"]")
          UPDATE_PAYLOAD=$(jq -n --arg fn "$FILE_NAME" --argjson c "$UPDATED_JSON" \
            '{files: {($fn): {content: ($c | tostring)}}}')
          
          curl -s -X PATCH -H "Authorization: token $GIST_TOKEN" \
            -H "Content-Type: application/json" \
            -d "$UPDATE_PAYLOAD" $GIST_API

          echo "Gist updated with @$LOGIN"
