name: Email CLA Contributor Post

on:
  pull_request:
    types: [closed]

jobs:
  email-wordpress-post:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Send draft blog post via email
        env:
          EMAIL_TO: ${{ secrets.WP_POST_BY_EMAIL }}
        run: |
          LOGIN="${{ github.event.pull_request.user.login }}"
          REPO="${{ github.repository }}"

          SUBJECT="New CLA Contributor: @$LOGIN"
          BODY="[status draft]\n\n@$LOGIN signed the CLA and contributed to \`$REPO\`.\nGitHub: https://github.com/$LOGIN"

          echo -e "Subject: $SUBJECT\n\n$BODY" | sendmail "$EMAIL_TO"
