name: Blog CLA Contributor

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  post-to-wordpress:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    env:
      WP_TOKEN: ${{ secrets.WP_TOKEN }}
      WP_SITE: ${{ secrets.WP_SITE }}

    steps:
      - name: Check if CLA check passed (via REST API)
        id: cla_check
        uses: actions/github-script@v7
        with:
          script: |
            const pr = context.payload.pull_request;
            const ref = pr.head.sha;

            const url = `https://api.github.com/repos/${context.repo.owner}/${context.repo.repo}/commits/${ref}/check-runs`;
            const res = await fetch(url, {
              headers: {
                Authorization: `Bearer ${process.env.GITHUB_TOKEN}`,
                Accept: 'application/vnd.github.v3+json'
              }
            });

            const data = await res.json();

            console.log("🔍 Found check runs:");
            data.check_runs.forEach(run => {
              console.log(`- ${run.name}: ${run.conclusion}`);
            });

            // Match any check run that contains 'cla' in its name and succeeded
            const passedCLA = data.check_runs.some(run =>
              run.name.toLowerCase().includes('cla') && run.conclusion === 'success'
            );

            console.log("✅ CLA check passed:", passedCLA);
            core.setOutput("cla_passed", passedCLA);
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Post to WordPress (avoid duplicates)
        if: steps.cla_check.outputs.cla_passed == 'true'
        run: |
          LOGIN="${{ github.event.pull_request.user.login }}"
          AVATAR="https://github.com/$LOGIN.png"
          PROFILE="https://github.com/$LOGIN"
          REPO="${{ github.repository }}"
          TITLE="New Contributor: @$LOGIN"
          CONTENT="<p><a href=\"$PROFILE\">@$LOGIN</a> signed the CLA and contributed to <code>$REPO</code>.</p><p><img src=\"$AVATAR\" style=\"max-width:100px;border-radius:50%;\" /></p>"

          echo "🔍 Checking WordPress for existing post about @$LOGIN..."

          EXISTS=$(curl -s -G \
            -H "Authorization: Bearer $WP_TOKEN" \
            --data-urlencode "search=@$LOGIN" \
            "https://public-api.wordpress.com/rest/v1.1/sites/$WP_SITE/posts/" \
            | jq '.posts | map(select(.title | contains("@'"$LOGIN"'"))) | length')

          if [ "$EXISTS" -eq 0 ]; then
            echo "📝 No post found. Publishing..."
            curl -X POST https://public-api.wordpress.com/rest/v1.1/sites/$WP_SITE/posts/new \
              -H "Authorization: Bearer $WP_TOKEN" \
              -H "Content-Type: application/json" \
              -d "$(jq -n --arg title "$TITLE" --arg content "$CONTENT" '{title: $title, content: $content, status: "publish"}')"
          else
            echo "✅ Contributor @$LOGIN already has a blog post. Skipping."
          fi
